{"labels": [{"name": "tag", "value": "login"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "15668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}], "historyId": "8c297d3530a4b2fa8edc344d628138ad", "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data3]", "uuid": "10e52a34-84e8-42d0-93ce-33c8e7346c0f", "start": 1561889725734, "name": "test_login_0_failed_by_wrong_datas[data3]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '1868472055', 'password': 'python', 'check': '请输入正确的手机号'}"}], "stop": 1561889726416}