{"status": "passed", "uuid": "a36258c0-8c39-4a15-9ecc-6f73804b7c79", "labels": [{"value": "login", "name": "tag"}, {"value": "test_login_pytest", "name": "suite"}, {"value": "TestLoginP", "name": "subSuite"}, {"value": "TestCases", "name": "parentSuite"}, {"value": "G50-75M", "name": "host"}, {"value": "18600-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "TestCases.test_login_pytest", "name": "package"}], "parameters": [{"value": "{'check': '请输入正确的手机号', 'user': '186847205531', 'password': 'python'}", "name": "data"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data2]", "historyId": "2ccd9b197d81af3dca9b411f49db3e45", "stop": 1561878681196, "start": 1561878680136, "name": "test_login_0_failed_by_wrong_datas[data2]"}