{"uuid": "d4c39c37-f5c4-4115-8124-82235b551bfc", "start": 1562387007231, "status": "passed", "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data2]", "name": "test_login_0_failed_by_wrong_datas[data2]", "stop": 1562387008291, "historyId": "2ccd9b197d81af3dca9b411f49db3e45", "parameters": [{"name": "data", "value": "{'user': '186847205531', 'check': '请输入正确的手机号', 'password': 'python'}"}], "labels": [{"name": "tag", "value": "login"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "17676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}]}