{"uuid": "f5c6a7a1-f649-4898-a4e8-68fc6820be10", "start": 1562387010303, "status": "passed", "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data4]", "name": "test_login_0_failed_by_wrong_datas[data4]", "stop": 1562387012395, "historyId": "0cd1a3fa99d0599dc61cd043dcb6fb74", "parameters": [{"name": "data", "value": "{'user': '1868472 0553', 'check': '请输入正确的手机号', 'password': 'python'}"}], "labels": [{"name": "tag", "value": "login"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "17676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}]}