{"uuid": "b64fc0f1-e618-4287-952a-c0fb699f97a6", "start": 1562387013147, "status": "passed", "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data5]", "name": "test_login_0_failed_by_wrong_datas[data5]", "stop": 1562387013851, "historyId": "930813980c1d67c94f4cedd1773e7594", "parameters": [{"name": "data", "value": "{'user': '186847aa553', 'check': '请输入正确的手机号', 'password': 'python'}"}], "labels": [{"name": "tag", "value": "login"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "17676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}]}