{"status": "passed", "uuid": "83e3d3ab-df71-4ff2-9463-35823f46b0b4", "labels": [{"value": "login", "name": "tag"}, {"value": "test_login_pytest", "name": "suite"}, {"value": "TestLoginP", "name": "subSuite"}, {"value": "TestCases", "name": "parentSuite"}, {"value": "G50-75M", "name": "host"}, {"value": "18600-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "TestCases.test_login_pytest", "name": "package"}], "parameters": [{"value": "{'check': '请输入密码', 'user': '18684720553', 'password': ''}", "name": "data"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data1]", "historyId": "80d9377c0bc951243a83d4fa54c0b331", "stop": 1561878679395, "start": 1561878678468, "name": "test_login_0_failed_by_wrong_datas[data1]"}