{"status": "passed", "uuid": "d3f5ec7d-14e4-400c-885e-603dbf09e7cf", "labels": [{"value": "login", "name": "tag"}, {"value": "test_login_pytest", "name": "suite"}, {"value": "TestLoginP", "name": "subSuite"}, {"value": "TestCases", "name": "parentSuite"}, {"value": "G50-75M", "name": "host"}, {"value": "18600-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "TestCases.test_login_pytest", "name": "package"}], "parameters": [{"value": "{'check': '请输入正确的手机号', 'user': '186847aa553', 'password': 'python'}", "name": "data"}], "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data5]", "historyId": "930813980c1d67c94f4cedd1773e7594", "stop": 1561878687164, "start": 1561878685657, "name": "test_login_0_failed_by_wrong_datas[data5]"}