{"labels": [{"name": "tag", "value": "login"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "15668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}], "historyId": "d1021337b075fdb88fea8a1fac58ed32", "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_1_failed_by_fail_datas[data0]", "uuid": "9fdc92ae-da83-4a29-8ebd-fb1a43ae0961", "start": 1561889729834, "name": "test_login_1_failed_by_fail_datas[data0]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '13200000000', 'password': 'python', 'check': '此账号没有经过授权，请联系管理员!'}"}], "stop": 1561889731285}